# Generated by Django 4.1.3 on 2023-02-13 04:19

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("musker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_modified",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name=django.contrib.auth.models.User,
            ),
            preserve_default=False,
        ),
    ]
